# CMS services
FIND_A_SUPPLIER = 'FIND_A_SUPPLIER'
EXPORT_READINESS = 'EXPORT_READINESS'
INVEST = 'INVEST'
COMPONENTS = 'COMPONENTS'

# CMS page slugs
COMPONENTS_BANNER_DOMESTIC_SLUG = 'eu-exit-banner-domestic'
COMPONENTS_BANNER_INTERNATIONAL_SLUG = 'eu-exit-banner-international'
# Export Readiness
EXPORT_READINESS_HOME_SLUG = 'home'
EXPORT_READINESS_HOME_INTERNATIONAL_SLUG = 'international'
EXPORT_READINESS_EUEXIT_FORM_SUCCESS_SLUG = 'eu-exit-form-success'
EXPORT_READINESS_EUEXIT_INTERNATIONAL_FORM_SLUG = 'eu-exit-international'
EXPORT_READINESS_EUEXIT_DOMESTIC_FORM_SLUG = 'eu-exit-domestic'
EXPORT_READINESS_TERMS_AND_CONDITIONS_SLUG = 'terms-and-conditions'
EXPORT_READINESS_PRIVACY_AND_COOKIES_SLUG = 'privacy-and-cookies'
EXPORT_READINESS_GET_FINANCE_SLUG = 'get-finance'
EXPORT_READINESS_HIGH_POTENTIAL_OPPORTUNITY_FORM_SLUG = (
    'high-potential-opportunity-form'
)
EXPORT_READINESS_HIGH_POTENTIAL_OPPORTUNITY_FORM_SUCCESS_SLUG = (
    'high-potential-opportunity-submit-success'
)
EXPORT_READINESS_HELP_EXOPP_ALERTS_IRRELEVANT_SLUG = 'alerts-not-relevant'
EXPORT_READINESS_HELP_MISSING_VERIFY_EMAIL_SLUG = 'no-verification-email'
EXPORT_READINESS_HELP_PASSWORD_RESET_SLUG = 'password-reset'
EXPORT_READINESS_HELP_COMPANIES_HOUSE_LOGIN_SLUG = 'companies-house-login'
EXPORT_READINESS_HELP_VERIFICATION_CODE_ENTER_SLUG = 'verification-letter-code'
EXPORT_READINESS_HELP_VERIFICATION_CODE_LETTER_SLUG = 'no-verification-letter'
EXPORT_READINESS_EU_EXIT_DOMESTIC_NEWS_SLUG = 'eu-exit-news'
EXPORT_READINESS_EU_EXIT_INTERNATIONAL_NEWS_SLUG = 'international-eu-exit-news'
EXPORT_READINESS_PERFORMANCE_DASHBOARD_SLUG = 'performance-dashboard'
EXPORT_READINESS_PERFORMANCE_DASHBOARD_EXOPPS_SLUG = (
    'performance-dashboard-export-opportunities'
)
EXPORT_READINESS_PERFORMANCE_DASHBOARD_SOO_SLUG = (
    'performance-dashboard-selling-online-overseas'
)
EXPORT_READINESS_PERFORMANCE_DASHBOARD_TRADE_PROFILE_SLUG = (
    'performance-dashboard-trade-profiles'
)
EXPORT_READINESS_PERFORMANCE_DASHBOARD_INVEST_SLUG = (
    'performance-dashboard-invest'
)
EXPORT_READINESS_PERFORMANCE_DASHBOARD_NOTES_SLUG = (
    'performance-dashboard-notes'
)
EXPORT_READINESS_CONTACT_US_FORM_SUCCESS_SLUG = 'contact-success-form'
EXPORT_READINESS_CONTACT_US_FORM_SUCCESS_EVENTS_SLUG = (
    'contact-events-success-form'
)
EXPORT_READINESS_CONTACT_US_FORM_SUCCESS_DSO_SLUG = (
    'contact-dso-success-form'
)
EXPORT_READINESS_CONTACT_US_FORM_SUCCESS_EXPORT_ADVICE_SLUG = (
    'contact-export-advice-success-form'
)
EXPORT_READINESS_CONTACT_US_FORM_SUCCESS_FEEDBACK_SLUG = (
    'contact-feedback-success-form'
)
EXPORT_READINESS_CONTACT_US_FORM_SUCCESS_FIND_COMPANIES_SLUG = (
    'contact-find-companies-success-form'
)
EXPORT_READINESS_CONTACT_US_FORM_SUCCESS_INTERNATIONAL_SLUG = (
    'contact-international-success-form'
)
# Find A Supplier
FIND_A_SUPPLIER_INDUSTRY_LANDING_SLUG = 'industries-landing-page'
FIND_A_SUPPLIER_LANDING_SLUG = 'landing-page'
FIND_A_SUPPLIER_INDUSTRY_CONTACT_SLUG = 'industry-contact'


# CMS page types
FIND_A_SUPPLIER_INDUSTRY_TYPE = 'find_a_supplier.IndustryPage'
FIND_A_SUPPLIER_INDUSTRY_ARTICLE_TYPE = 'find_a_supplier.IndustryArticlePage'
