# CMS services
FIND_A_SUPPLIER = 'FIND_A_SUPPLIER'
EXPORT_READINESS = 'EXPORT_READINESS'
INVEST = 'INVEST'
COMPONENTS = 'COMPONENTS'

# CMS page slugs
COMPONENTS_BANNER_DOMESTIC_SLUG = 'eu-exit-banner-domestic'
COMPONENTS_BANNER_INTERNATIONAL_SLUG = 'eu-exit-banner-international'
EXPORT_READINESS_EUEXIT_FORM_SUCCESS_SLUG = 'eu-exit-form-success'
EXPORT_READINESS_EUEXIT_INTERNATIONAL_FORM_SLUG = 'eu-exit-international'
EXPORT_READINESS_EUEXIT_DOMESTIC_FORM_SLUG = 'eu-exit-domestic'
EXPORT_READINESS_TERMS_AND_CONDITIONS_SLUG = 'terms-and-conditions'
EXPORT_READINESS_PRIVACY_AND_COOKIES_SLUG = 'privacy-and-cookies'
EXPORT_READINESS_GET_FINANCE_SLUG = 'get-finance'
EXPORT_READINESS_HIGH_POTENTIAL_OPPORTUNITY_FORM_SLUG = (
    'high-potential-opportunity-form'
)
EXPORT_READINESS_HIGH_POTENTIAL_OPPORTUNITY_FORM_SUCCESS_SLUG = (
    'high-potential-opportunity-submit-success'
)
EXPORT_READINESS_GUIDANCE_EXPORT_OPPORTUNITIES_ALERTS_NOT_RELEVANT_SLUG = (
    'alerts-not-relevant'
)
EXPORT_READINESS_EU_EXIT_DOMESTIC_NEWS_SLUG = 'eu-exit-news'
EXPORT_READINESS_EU_EXIT_INTERNATIONAL_NEWS_SLUG = 'international-eu-exit-news'
FIND_A_SUPPLIER_INDUSTRY_LANDING_SLUG = 'industries-landing-page'
FIND_A_SUPPLIER_LANDING_SLUG = 'landing-page'
FIND_A_SUPPLIER_INDUSTRY_CONTACT_SLUG = 'industry-contact'

# CMS page types
FIND_A_SUPPLIER_INDUSTRY_TYPE = 'find_a_supplier.IndustryPage'
FIND_A_SUPPLIER_INDUSTRY_ARTICLE_TYPE = 'find_a_supplier.IndustryArticlePage'
