version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test_requirements
            make test
  publish_to_pypi:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-dev.txt" }}-{{ checksum "setup.py" }}
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test_requirements
            make publish
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}-{{ checksum "setup.py" }}

workflows:
  version: 2
  test_and_publish_to_pypi:
    jobs:
      - test
      - publish_to_pypi:
          requires:
            - test
          filters:
            branches:
              only: master
