# CMS services
FIND_A_SUPPLIER = 'FIND_A_SUPPLIER'
GREAT_DOMESTIC = EXPORT_READINESS = 'EXPORT_READINESS'
INVEST = 'INVEST'
COMPONENTS = 'COMPONENTS'
GREAT_INTERNATIONAL = 'GREAT_INTERNATIONAL'

# CMS page types
FIND_A_SUPPLIER_INDUSTRY_TYPE = 'find_a_supplier.IndustryPage'
FIND_A_SUPPLIER_INDUSTRY_ARTICLE_TYPE = 'find_a_supplier.IndustryArticlePage'
