# Constants for route to market
MARKETING_AT_EVENTS = 'MARKETING_AT_EVENTS'
ONLINE_MARKETING = 'ONLINE_MARKETING'
OTHER = 'OTHER'

# Constants for product promotion
DIRECT_SALES = 'DIRECT_SALES'
INTERNATIONAL_E_COMMERCE = 'INTERNATIONAL_E_COMMERCE'
AGENT_OR_DISTRIBUTOR = 'AGENT_OR_DISTRIBUTOR'
LICENSING = 'LICENSING'
FRANCHISING = 'FRANCHISING'
JOINT_VENTURES = 'JOINT_VENTURES'
SET_UP_A_BUSINESS_ABROAD = 'SET_UP_A_BUSINESS_ABROAD'
