# Constants Funding Option
BANK_LOAN = 'BANK_LOAN'
GOVERNMENT = 'GOVERNMENT'
FINANCE_PLATFORMS = 'FINANCE_PLATFORMS'
PEER_TO_PEER_LOANS = 'PEER_TO_PEER_LOANS'
EQUITY_FINANCE = 'EQUITY_FINANCE'

# Constants for transport options
EX_WORKS = 'EX_WORKS'
FREE_CARRIER = 'FREE_CARRIER'
CARRIER_INSURANCE_PAID = 'CARRIER_INSURANCE_PAID'
DELIVERED_PLACE_UNLOADED = 'DELIVERED_PLACE_UNLOADED'
DELIVERED_AT_PLACE = 'DELIVERED_AT_PLACE'
DELIVERED_DUTY_PAID = 'DELIVERED_DUTY_PAID'

# Constants for water transport options
FREE_ALONG_SHIP = 'FREE_ALONG_SHIP'
FREE_ON_BOARD = 'FREE_ON_BOARD'
COST_AND_FREIGHT = 'COST_AND_FREIGHT'
COST_INSURANCE_FREIGHT = 'COST_INSURANCE_FREIGHT'

# Constants for payment options
INTERNATIONAL_BANK_TRANSFER = 'INTERNATIONAL_BANK_TRANSFER'
CREDIT_DEBIT = 'CREDIT_DEBIT'
MERCHANT_SERVICES = 'MERCHANT_SERVICES'
LOCAL_BANK_TRANSFERS = 'LOCAL_BANK_TRANSFERS'

# Constants for payment terms
PAYMENT_IN_ADVANCE = 'PAYMENT_IN_ADVANCE'
LETTER_OF_CREDIT = 'LETTER_OF_CREDIT'
BANK_DOCUMENTARY_COLLECTION = 'BANK_DOCUMENTARY_COLLECTION'
OPEN_ACCOUNT = 'OPEN_ACCOUNT'

# General constants
OTHER = 'OTHER'

# Risk Likelihood
RARE = 'RARE'
UNLIKELY = 'UNLIKELY'
POSSIBLE = 'POSSIBLE'
LIKELY = 'LIKELY'
CERTAIN = 'CERTAIN'

# Risk Impact
TRIVIAL = 'TRIVIAL'
MINOR = 'MINOR'
MODERATE = 'MODERATE'
MAJOR = 'MAJOR'
SEVERE = 'SEVERE'
