AUTOMOTIVE = 'AUTOMOTIVE'
ADVANCED_MANUFACTURING = 'ADVANCED_MANUFACTURING'
AEROSPACE = 'AEROSPACE'
AGRICULTURE_HORTICULTURE_AND_FISHERIES = (
    'AGRICULTURE_HORTICULTURE_AND_FISHERIES'
)
AIRPORTS = 'AIRPORTS'
BIOTECHNOLOGY_AND_PHARMACEUTICALS = 'BIOTECHNOLOGY_AND_PHARMACEUTICALS'
BUSINESS_AND_CONSUMER_SERVICES = 'BUSINESS_AND_CONSUMER_SERVICES'
CHEMICALS = 'CHEMICALS'
CLOTHING_FOOTWEAR_AND_FASHION = 'CLOTHING_FOOTWEAR_AND_FASHION'
COMMUNICATIONS = 'COMMUNICATIONS'
CONSTRUCTION = 'CONSTRUCTION'
CREATIVE_AND_MEDIA = 'CREATIVE_AND_MEDIA'
EDUCATION_AND_TRAINING = 'EDUCATION_AND_TRAINING'
ELECTRONICS_AND_IT_HARDWARE = 'ELECTRONICS_AND_IT_HARDWARE'
ENVIRONMENT = 'ENVIRONMENT'
FINANCIAL_AND_PROFESSIONAL_SERVICES = 'FINANCIAL_AND_PROFESSIONAL_SERVICES'
FOOD_AND_DRINK = 'FOOD_AND_DRINK'
GIFTWARE_JEWELLERY_AND_TABLEWARE = 'GIFTWARE_JEWELLERY_AND_TABLEWARE'
GLOBAL_SPORTS_INFRASTRUCTURE = 'GLOBAL_SPORTS_INFRASTRUCTURE'
HEALTHCARE_AND_MEDICAL = 'HEALTHCARE_AND_MEDICAL'
HOUSEHOLD_GOODS_FURNITURE_AND_FURNISHINGS = (
    'HOUSEHOLD_GOODS_FURNITURE_AND_FURNISHINGS'
)
LEGAL_SERVICES = 'LEGAL_SERVICES'
LEISURE_AND_TOURISM = 'LEISURE_AND_TOURISM'
LIFE_SCIENCES = 'LIFE_SCIENCES'
MARINE = 'MARINE'
MECHANICAL_ELECTRICAL_AND_PROCESS_ENGINEERING = (
    'MECHANICAL_ELECTRICAL_AND_PROCESS_ENGINEERING'
)
METALLURGICAL_PROCESS_PLANT = 'METALLURGICAL_PROCESS_PLANT'
METALS_MINERALS_AND_MATERIALS = 'METALS_MINERALS_AND_MATERIALS'
MINING = 'MINING'
OIL_AND_GAS = 'OIL_AND_GAS'
PORTS_AND_LOGISTICS = 'PORTS_AND_LOGISTICS'
POWER = 'POWER'
RAILWAYS = 'RAILWAYS'
RENEWABLE_ENERGY = 'RENEWABLE_ENERGY'
RETAIL_AND_LUXURY = 'RETAIL_AND_LUXURY'
SECURITY = 'SECURITY'
SOFTWARE_AND_COMPUTER_SERVICES = 'SOFTWARE_AND_COMPUTER_SERVICES'
TEXTILES_INTERIOR_TEXTILES_AND_CARPETS = (
    'TEXTILES_INTERIOR_TEXTILES_AND_CARPETS'
)
WATER = 'WATER'


# marketing pages refer to these conflated groups of sectors
ADVANCED_MANUFACTURING = 'ADVANCED_MANUFACTURING'
CONSUMER_AND_RETAIL = 'CONSUMER_AND_RETAIL'
ENERGY = 'ENERGY'
LIFE_SCIENCES_AND_HEALTHCARE = 'LIFE_SCIENCES_AND_HEALTHCARE'
TECHNOLOGY = 'TECHNOLOGY'
INFRASTRUCTURE = 'INFRASTRUCTURE'
PROFESSIONAL_SERVIVES = 'PROFESSIONAL_SERVIVES'
CYBER_SECURITY = 'CYBER_SECURITY'
BIO_ECONOMY = 'BIO_ECONOMY'
SMART_CITIES = 'SMART_CITIES'
LEGAL = 'LEGAL'

CONFLATED = {
    ADVANCED_MANUFACTURING: (
        MECHANICAL_ELECTRICAL_AND_PROCESS_ENGINEERING,
        METALLURGICAL_PROCESS_PLANT,
        METALS_MINERALS_AND_MATERIALS,
        MINING,
    ),
    CONSUMER_AND_RETAIL: (
        CLOTHING_FOOTWEAR_AND_FASHION,
        GIFTWARE_JEWELLERY_AND_TABLEWARE,
        HOUSEHOLD_GOODS_FURNITURE_AND_FURNISHINGS,
        TEXTILES_INTERIOR_TEXTILES_AND_CARPETS,
    ),
    ENERGY: (
        OIL_AND_GAS,
        RENEWABLE_ENERGY,
        POWER,
        WATER,
    ),
    LIFE_SCIENCES_AND_HEALTHCARE: (
        BIOTECHNOLOGY_AND_PHARMACEUTICALS,
        HEALTHCARE_AND_MEDICAL,
    ),
    TECHNOLOGY: (
        COMMUNICATIONS,
        ELECTRONICS_AND_IT_HARDWARE,
        SOFTWARE_AND_COMPUTER_SERVICES,
    ),
    INFRASTRUCTURE: (
        AIRPORTS,
        CONSTRUCTION,
        LEISURE_AND_TOURISM,
        MARINE,
        PORTS_AND_LOGISTICS,
        RAILWAYS,
    ),
    PROFESSIONAL_SERVIVES: (
        BUSINESS_AND_CONSUMER_SERVICES,
        EDUCATION_AND_TRAINING,
        FINANCIAL_AND_PROFESSIONAL_SERVICES,
    ),
    CYBER_SECURITY: (
        COMMUNICATIONS,
        ELECTRONICS_AND_IT_HARDWARE,
        SECURITY,
        SOFTWARE_AND_COMPUTER_SERVICES,
    ),
    BIO_ECONOMY: (
        AGRICULTURE_HORTICULTURE_AND_FISHERIES,
        CHEMICALS,
    ),
    SMART_CITIES: (
        ELECTRONICS_AND_IT_HARDWARE,
        SOFTWARE_AND_COMPUTER_SERVICES,
    ),
    LEGAL: (
        FINANCIAL_AND_PROFESSIONAL_SERVICES,
        LEGAL_SERVICES,
    ),
}
